name: Format Code

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ktfmt
        run: |
          curl -L https://github.com/facebookincubator/ktfmt/releases/latest/download/ktfmt -o ktfmt
          chmod +x ktfmt
          sudo mv ktfmt /usr/local/bin/

      - name: Format code
        run: ktfmt --format -r .

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-format code using ktfmt"

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
